### ISSUE TITLE
Failed to open pcap device

### ISSUE THREAD

**Issue by liushiqi1001** [masa10249chi/mptcp-go#1]
Hello, according to the tutorial, I have compiled the binary file successfully. 

But when I execute the command :
`./server_mptcp-tunneling -server_ip 0.0.0.0 -server_port 4321`

it outputs:
`Server start ! (Server: 0.0.0.0:4321)
Failed to open pcap device.
`

**Comment by liushiqi1001** [comment]
My Linux version is Ubuntu 22.04.

**Comment by masa10249chi** [comment]
Hello, liushiqi1001-san. Thank you for trying my program.

I had a mistake and I had left the pcap device hard coded in the code.
So could you try replacing the 85th line of server_mptcp-tunneling.go with the value of your environment?

**Comment by liushiqi1001** [comment]
The client is reporting an error at line 116, with the error message '
`protocol not available'`

![image](https://user-images.githubusercontent.com/28683522/227453079-e6f37038-16a6-49a5-8844-2f1fb3a5046e.png)

now，server is running
![image](https://user-images.githubusercontent.com/28683522/227453205-b6042c9c-79bc-4874-91df-7d5e4346220d.png)

**Comment by liushiqi1001** [comment]
I'm sorry, I was running both the server and the client on the same machine, but now it's working properly.

**Comment by liushiqi1001** [comment]
thinks！！！
